from aiogram.types import ReplyKeyboardRemove, \
    ReplyKeyboardMarkup, KeyboardButton, \
    InlineKeyboardMarkup, InlineKeyboardButton

##0(1,2)
inline_kb_full_0= InlineKeyboardMarkup(row_width=2)
inline_btn_a1 = InlineKeyboardButton('💬Социальные сети', callback_data='btna1')
inline_btn_a2 = InlineKeyboardButton('📍Контакты и адрес', callback_data='btna2')
inline_btn_a3 = InlineKeyboardButton('🛎️Каталог услуг', callback_data='btna3')
inline_btn_a4 = InlineKeyboardButton('🗺️Визы', callback_data='btna4')
inline_btn_a5 = InlineKeyboardButton('💸Способы оплаты', callback_data='btna5')
inline_btn_a6 = InlineKeyboardButton('⁉️Оставить отзыв', callback_data='btna6')
inline_kb_full_0.row(inline_btn_a1)
inline_kb_full_0.row(inline_btn_a2)
inline_kb_full_0.row(inline_btn_a3)
inline_kb_full_0.row(inline_btn_a4)
inline_kb_full_0.row(inline_btn_a5)
inline_kb_full_0.row(inline_btn_a6)


##0(1,2)
inline_kb_full_b= InlineKeyboardMarkup(row_width=2)
inline_btn_b1 = InlineKeyboardButton('Телеграм', callback_data='btnb1')
inline_btn_b2 = InlineKeyboardButton('Востап', callback_data='btnb2')
inline_btn_b3 = InlineKeyboardButton('Сайт', callback_data='btnb3')
inline_btn_b4 = InlineKeyboardButton('Почта', callback_data='btnb4')
inline_btn_back = InlineKeyboardButton('Назад', callback_data='btn00')
inline_kb_full_b.row(inline_btn_b1)
inline_kb_full_b.row(inline_btn_b2)
inline_kb_full_b.row(inline_btn_b3)
inline_kb_full_b.row(inline_btn_b4)
inline_kb_full_b.row(inline_btn_back)

##0(1,2)
inline_kb_full_с= InlineKeyboardMarkup(row_width=2)
inline_btn_back = InlineKeyboardButton('Назад', callback_data='btn00')
inline_kb_full_с.row(inline_btn_back)

##0(1,2)
inline_kb_full_d= InlineKeyboardMarkup(row_width=2)
inline_btn_d1 = InlineKeyboardButton('🎟️ JR Pass', callback_data='btnd1')
inline_btn_d2 = InlineKeyboardButton('🛜 Wi-Fi роутер в Японии ', callback_data='btnd2')
inline_btn_d3 = InlineKeyboardButton('🌏 Туры', callback_data='btnd3')
inline_btn_d4 = InlineKeyboardButton('🛩 Авиабилеты ', callback_data='btnd4')
inline_btn_d5 = InlineKeyboardButton('🚅 Ж/Д билеты ', callback_data='btnd5')
inline_btn_d6 = InlineKeyboardButton('🏨 Отели ', callback_data='btnd6')
inline_btn_d7 = InlineKeyboardButton('🛳️ Паромы ', callback_data='btnd7')
inline_btn_d8 = InlineKeyboardButton('🌐 Визы ', callback_data='btnd8')
inline_btn_back = InlineKeyboardButton('Назад', callback_data='btn00')
inline_kb_full_d.row(inline_btn_d1)
inline_kb_full_d.row(inline_btn_d2)
inline_kb_full_d.row(inline_btn_d3)
inline_kb_full_d.row(inline_btn_d4)
inline_kb_full_d.row(inline_btn_d5)
inline_kb_full_d.row(inline_btn_d6)
inline_kb_full_d.row(inline_btn_d7)
inline_kb_full_d.row(inline_btn_d8)
inline_kb_full_d.row(inline_btn_back)


##0(1,2)
inline_kb_full_e= InlineKeyboardMarkup(row_width=2)
inline_btn_e1 = InlineKeyboardButton('🇨🇳 Китай', callback_data='btne1')
inline_btn_e2 = InlineKeyboardButton('🇯🇵 Япония', callback_data='btne2')
inline_btn_e3 = InlineKeyboardButton('🇰🇷 Республика Корея', callback_data='btne3')
inline_btn_e4 = InlineKeyboardButton('🌐 Другие страны', callback_data='btne4')
inline_btn_back = InlineKeyboardButton('Назад', callback_data='btn00')
inline_kb_full_e.row(inline_btn_e1)
inline_kb_full_e.row(inline_btn_e2)
inline_kb_full_e.row(inline_btn_e3)
inline_kb_full_e.row(inline_btn_e4)
inline_kb_full_e.row(inline_btn_back)


##0(1,2)
inline_kb_full_f= InlineKeyboardMarkup(row_width=2)
inline_btn_f1 = InlineKeyboardButton('Связаться с менеджером', callback_data='btnf1')
inline_btn_back = InlineKeyboardButton('Назад', callback_data='btn00')
inline_kb_full_f.row(inline_btn_f1)
inline_kb_full_f.row(inline_btn_back)

##0(1,2)
inline_kb_full_g= InlineKeyboardMarkup(row_width=2)
inline_btn_g1 = InlineKeyboardButton('Связаться с менеджером', callback_data='btng1')
inline_btn_back = InlineKeyboardButton('Назад', callback_data='btn00')
inline_kb_full_g.row(inline_btn_g1)
inline_kb_full_g.row(inline_btn_back)


##0(1,2)
inline_kb_full_06= InlineKeyboardMarkup(row_width=2)
inline_btn_060 = InlineKeyboardButton('⬅️ назад', callback_data='btn060')
inline_btn_061 = InlineKeyboardButton('1', callback_data='btn061')
inline_btn_062 = InlineKeyboardButton('2', callback_data='btn062')
inline_btn_063 = InlineKeyboardButton('3', callback_data='btn063')
inline_btn_064 = InlineKeyboardButton('4', callback_data='btn064')
inline_btn_065 = InlineKeyboardButton('5', callback_data='btn065')
inline_btn_066 = InlineKeyboardButton('6', callback_data='btn066')
inline_kb_full_06.row(inline_btn_061)
inline_kb_full_06.row(inline_btn_062)
inline_kb_full_06.row(inline_btn_063)
inline_kb_full_06.row(inline_btn_064)
inline_kb_full_06.row(inline_btn_065)
inline_kb_full_06.row(inline_btn_066)
inline_kb_full_06.row(inline_btn_060)


##0(1,2)
inline_kb_full_06b= InlineKeyboardMarkup(row_width=2)
inline_btn_06b1 = InlineKeyboardButton('⬅️ Назад', callback_data='btn06')
inline_kb_full_06b.row(inline_btn_06b1)


##0(1,2)
inline_kb_full_08= InlineKeyboardMarkup(row_width=2)
inline_btn_081 = InlineKeyboardButton('🆗 Отлично', callback_data='btn081')
inline_btn_082 = InlineKeyboardButton('⬅️ Назад', callback_data='btn00')
inline_kb_full_08.row(inline_btn_081)
inline_kb_full_08.row(inline_btn_082)

##0(1,2)
inline_kb_full_082= InlineKeyboardMarkup(row_width=2)
inline_btn_0821 = InlineKeyboardButton('🆗 Записываемся дальше', callback_data='btn0821')
inline_kb_full_082.row(inline_btn_0821)

##0(1,2)
inline_kb_full_083= InlineKeyboardMarkup(row_width=2)
inline_btn_0831 = InlineKeyboardButton('🆗 Записываемся дальше', callback_data='btn0831')
inline_kb_full_083.row(inline_btn_0821)


##0(1,2)
inline_kb_full_0b= InlineKeyboardMarkup(row_width=2)
inline_btn_0b1 = InlineKeyboardButton('⬅️ Назад', callback_data='btn00')
inline_kb_full_0b.row(inline_btn_0b1)


##0(1,2)
inline_kb_full_01= InlineKeyboardMarkup(row_width=2)
inline_btn_010 = InlineKeyboardButton('⬅️ Назад', callback_data='btn00')
inline_btn_011 = InlineKeyboardButton('✈️🌏', callback_data='btn011')
inline_btn_012 = InlineKeyboardButton('🧑‍💼🍽️', callback_data='btn012')
inline_btn_013 = InlineKeyboardButton('🍀🏭', callback_data='btn013')
inline_btn_014 = InlineKeyboardButton('🧑‍🏫🗺️', callback_data='btn014')
inline_kb_full_01.row(inline_btn_011)
inline_kb_full_01.row(inline_btn_012)
##inline_kb_full_01.row(inline_btn_013)
##inline_kb_full_01.row(inline_btn_014)
inline_kb_full_01.row(inline_btn_010)


##0(1,2)
inline_kb_full_01nb= InlineKeyboardMarkup(row_width=2)
inline_btn_01nb1 = InlineKeyboardButton('Спасибо, скорее приду', callback_data='btn01ny')
inline_btn_01nb2 = InlineKeyboardButton('Спасибо, скорее не приду', callback_data='btn01nn')
inline_kb_full_01nb.row(inline_btn_01nb1)
inline_kb_full_01nb.row(inline_btn_01nb2)

##0(1,2)
inline_kb_full_01b= InlineKeyboardMarkup(row_width=2)
inline_btn_01b1 = InlineKeyboardButton('Скорее интересно', callback_data='btn01y')
inline_btn_01b2 = InlineKeyboardButton('Скорее неинтересно', callback_data='btn01n')
inline_kb_full_01b.row(inline_btn_01b1)
inline_kb_full_01b.row(inline_btn_01b2)

##0(1,2)
inline_kb_full_0fb= InlineKeyboardMarkup(row_width=2)
inline_btn_0fb0 = InlineKeyboardButton('🔀 Еще факт!', callback_data='btn03')
inline_btn_0fb1 = InlineKeyboardButton('⬅️ Назад', callback_data='btn00')
inline_kb_full_0fb.row(inline_btn_0fb0)
inline_kb_full_0fb.row(inline_btn_0fb1)


##3(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,!5,16)
inline_kb_full_DL = InlineKeyboardMarkup(row_width=1)
inline_btn_DL0 = InlineKeyboardButton('0', callback_data='btnDL0')
inline_btn_DL1 = InlineKeyboardButton('1', callback_data='btnDL1')
inline_btn_DL2 = InlineKeyboardButton('2', callback_data='btnDL2')
inline_btn_DL3 = InlineKeyboardButton('3', callback_data='btnDL3')
inline_btn_DL4 = InlineKeyboardButton('4', callback_data='btnDL4')
inline_btn_DL5 = InlineKeyboardButton('5', callback_data='btnDL5')
inline_kb_full_DL.row(inline_btn_DL0, inline_btn_DL1, inline_btn_DL2, inline_btn_DL3, inline_btn_DL4, inline_btn_DL5)

inline_kb_full_PDL = InlineKeyboardMarkup(row_width=1)
inline_btn_PDL1 = InlineKeyboardButton('🔙Вернуться в начало', callback_data='btnPDL1')
#inline_btn_PDL2 = InlineKeyboardButton('Вернуться к выбору дней', callback_data='btn2A')
inline_kb_full_PDL.row(inline_btn_PDL1)
#inline_kb_full_PDL.row(inline_btn_PDL2)

##0(1,2)
inline_kb_full_r4c= InlineKeyboardMarkup(row_width=2)
inline_btn_r4c1 = InlineKeyboardButton('Да', callback_data='btnr4c1')
inline_btn_r4c2 = InlineKeyboardButton('Нет', callback_data='btnr4c2')
inline_kb_full_r4c.row(inline_btn_r4c1)
inline_kb_full_r4c.row(inline_btn_r4c2)


##0(1,2)
inline_kb_full_0pb= InlineKeyboardMarkup(row_width=2)
inline_btn_0pb0 = InlineKeyboardButton('🔀 Еще факт!', callback_data='btn09b')
inline_btn_0pb1 = InlineKeyboardButton('⬅️ Назад', callback_data='btn00')
inline_kb_full_0pb.row(inline_btn_0pb0)
inline_kb_full_0pb.row(inline_btn_0pb1)